[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[db]
db_name = “airflow-classify”
db_conn_id = "AIRFLOW_CONN_AWS_RDS_POSTGRES"
db_connection = "postgresql+psycopg2://robert_su:12341234@rds_endpoint:5432/airflow-classify"
db_alchemy_driver = "postgresql+psycopg2"

[files]
s3_bucket = "de300spring2024-airflow"
s3_file_key = "wine.csv"


[ml]
train_test_ratio = 0.2
outliers_std_factor = 3
labels = "quality"
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95
